### PR TITLE
roll the version so we can release new package with MIT license.

### PR DESCRIPTION
**Pull request by jasells**
Forgot to roll versions to allow for us to release a package with new license.

### CODE REVIEW

**Comment by jasells** [comment]
Well, this is why build scripts shouldn't be in the repo.  They are better managed separately.  I can't figure out how to update the build script to install .Net5.0 because it is using the script from master when it does the CI build...

**Comment by jasells** [comment]
Ok, got the check build to pass, how do we set up an automated release?

**Comment by jasells** [comment]
And should squash this merge, it is pretty messy

**Comment by janusw** [comment]
> And should squash this merge, it is pretty messy

Agreed. I will take care of preparing a new release.

**Pull request closed without merging**
