### PR TITLE
Release 1.0.3

### PR DESCRIPTION
**Pull request by janusw**
This PR fixes a problem with the unit tests and bumps the version number (addressing #6).

@MatejFranceskin @jasells Are you ok with this?

### CODE REVIEW

**Review by jasells — APPROVED** [review]
Looks good.

I'm not familiar with how to complete a PR on github...  I don't see anything obvious, is it waiting for all of our approval?

**Comment by jasells** [comment]
Hmmmm, briefly looking @ the Github actions, it looks like we'll need to add a yaml script file in a particular repo sub-dir to start out. https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions

Do we want to work that into this PR too?

This is all new on github for me.  I could set this up in about 1 hr or less on DevOps building, publishing test results and pushing the package.  All the build stuff is kept outside of the repo there.

We *could* use DevOps for the CI build of this repo.  The down side is the split environment, but that would be less work for me.

**Comment by janusw** [comment]
> Looks good.
> 
> I'm not familiar with how to complete a PR on github... I don't see anything obvious, is it waiting for all of our approval?

Well, since you left a positive review, I will just merge it into master. It does not necessarily need everybody's approval, a single one should be sufficient. Btw, I'm not sure if you are able to do merges in this repo, maybe the permissions are not yet set up sufficiently.

**Comment by janusw** [comment]
> Hmmmm, briefly looking @ the Github actions, it looks like we'll need to add a yaml script file in a particular repo sub-dir to start out. https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
> 
> Do we want to work that into this PR too?

I don't think we need to include the CI setup in this PR. It can be done separately.

> This is all new on github for me. I could set this up in about 1 hr or less on DevOps building, publishing test results and pushing the package. All the build stuff is kept outside of the repo there.
> 
> We _could_ use DevOps for the CI build of this repo. The down side is the split environment, but that would be less work for me.

When you're talking about "DevOps" here, you mean Azure DevOps, right? The advantage of Github Actions from my point of view is that everything is done directly on Github and one does not need accounts/permissions for a second platform (I currently don't have one for Azure). I also like the idea of having the CI config in a yaml file in the repo, so that everything is in one place.

If you agree, I can try to set up Github actions for GeoidHeightsDotNet soon. Otherwise you can do the setup for Azure, if you like.

The more important question for the moment is how and where to publish the nupkg:
* With @MatejFranceskin's existing account on nuget.org (which only he can do, of course).
* With a different (shared?) acount on nuget.org.
* In our org on Github (https://github.com/orgs/GeoidHeightsDotNet/packages). This might require people to add the corresponding package source to their config, I believe.

Any opinions on that? Maybe I'll start with the last option, and we'll see whether we can also mirror the nupkg on nuget.org ...?

**Comment by MatejFranceskin** [comment]
I can add you as package owners on NuGet. I found user jasells but not
Janus.

**Comment by janusw** [comment]
> I can add you as package owners on NuGet.

That would be great. Thanks!


> I found user jasells but not Janus.

I did not have a nuget.org account yet, but just created one now: https://www.nuget.org/profiles/janusw

**Comment by MatejFranceskin** [comment]
Check if you got an invitation.

**Comment by janusw** [comment]
> Check if you got an invitation.

I did, and I already accepted it. Thanks! 😄

I'll try to upload the release 1.0.3 package now, if you don't mind ...

**Comment by MatejFranceskin** [comment]
Thanks for taking care of it!

**Pull request merged**
