### PR TITLE
port to .NET core

### PR DESCRIPTION
**Pull request by janusw**
This PR ports the GeoidHeightsDotNet library from the .NET framework to .NET core, which fixes the compatibility problems of issue #1.
Fortunately no actual code changes are necessary, only the project files are updated. In addition the Nuget.Packager project is removed, since Visual Studio can directly create nuget packages for .NET core projects.

### CODE REVIEW

**Review by MatejFranceskin — APPROVED** [review]
Great! Thank you very much.

**Comment by janusw** [comment]
Thanks a lot for merging this so quickly! Could you please make the updated nupkg available at nuget.org? (https://www.nuget.org/packages/GeoidHeightsDotNet/)

And maybe it would make sense to add a tag to the github repo for version 1.0.2?

**Comment by MatejFranceskin** [comment]
Yes, I am trying to create new package. Have to remember how. :-)

**Comment by janusw** [comment]
I work on Mac OS. What I do to create the package is open the GeoidHeightsDotNet solution in VS for Mac, right-click on the GeoidHeights project and choose "pack". This will generate a file `GeoidHeights/bin/Release/GeoidHeightsDotNet.1.0.2.nupkg`.

I tried to attach the file here, but apparently github does not support that file type. Please let me know in case you have further trouble to generate the nupkg.

**Comment by janusw** [comment]
> I work on Mac OS. What I do to create the package is open the GeoidHeightsDotNet solution in VS for Mac, right-click on the GeoidHeights project and choose "pack". This will generate a file `GeoidHeights/bin/Release/GeoidHeightsDotNet.1.0.2.nupkg`.

I verified that this also works in VS2019 on Windows.

**Comment by MatejFranceskin** [comment]
I couldn't build it with VS2017, but I switched to 2019.
Pushed package 1.0.2, please check if everything is ok.

**Comment by janusw** [comment]
> Pushed package 1.0.2, please check if everything is ok.

Works great, thank you! 😁

**Comment by janusw** [comment]
Just one thing I noticed: Some of the metadata for nuget was still missing, in particular the project URL (which is currently not shown on nuget.org) etc. See #3.

**Pull request merged**
